// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/gift.tsx";
import * as $2 from "./routes/stamp.tsx";
import * as $$0 from "./islands/gift.tsx";
import * as $$1 from "./islands/input.tsx";
import * as $$2 from "./islands/stamp.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/gift.tsx": $1,
    "./routes/stamp.tsx": $2,
  },
  islands: {
    "./islands/gift.tsx": $$0,
    "./islands/input.tsx": $$1,
    "./islands/stamp.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
